config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehiculos.urls')),
]

vehiculos/urls.py
from django.urls import path

from .views import index, v_add, v_list

urlpatterns = [
    path('', index),
    path('vehiculo/add', v_add),
    path('vehiculo/list', v_list),
]

vehiculos/models.py
from django.db import models


# Create your models here.
class Vehiculo(models.Model):
    marcas = [["Abarth", "Abarth"], ["BMW", "BMW"], ["Dacia", "Dacia"], ["Infiniti", "Infiniti"], ["Kia", "Kia"], ["Land Rover", "Land Rover"], ["Mercedes-Benz", "Mercedes-Benz"], ["Opel", "Opel"], ["Rolls-Royce", "Rolls-Royce"], ["Subaru", "Subaru"], ["Volkswagen", "Volkswagen"], ["Alfa Romeo", "TAlfa Romeo"], ["Cadillac", "Cadillac"], ["Ferrari", "Ferrari"], ["Isuzu", "Isuzu"], ["KTM", "KTM"], ["Lexus", "Lexus"], ["Mini", "Mini"], ["Peugeot", "Peugeot"], ["Seat", "Seat"], ["Suzuki", "Suzuki"], ["Volvo", "Volvo"], ["Aston Martin", "Aston Martin"], ["Toyota", "Toyota"], ["Caterham", "Caterham"], ["Iveco", "Iveco"], ["Lada", "Lada"], ["Lotus", "Lotus"], ["Fiat", "Fiat"], ["Mitsubishi", "Mitsubishi"], ["Piaggio", "Piaggio"], ["Skoda", "Skoda"], ["Tata", "Tata"], ["Audi", "Audi"], ["Jaguar", "Jaguar"], ["Lamborghini", "Lamborghini"], ["Maserati", "Maserati"], ["Chevrolet", "Chevrolet"], ["Ford", "Ford"], ["Morgan", "Morgan"], ["Porsche", "Porsche"], ["Smart", "Smart"], ["Tesla", "Tesla"], ["Bentley", "Bentley"], ["Citroen", "Citroen"], ["Honda", "Honda"], ["Jeep", "Jeep"], ["Lancia", "Lancia"], ["Mazda", "Mazda"], ["Nissan", "Nissan"], ["Renault", "Renault"], ["SsangYong", "SsangYong"], ["Toyota", "Toyota"]]
    marca = models.CharField(max_length=20, choices=marcas, default="Ford")
    modelo = models.CharField(max_length=20)
    condiciones = [["Nuevo", "Nuevo"], ["Seminuevo", "Seminuevo"], ["Usado", "Usado"]]
    condicion = models.CharField(max_length=20, 
                                 choices=condiciones, 
                                 default="Nuevo")
    año = models.CharField(max_length=5, default="2024")
    categorias = [["Particular", "Particular"], ["Transporte", "Transporte"],
                  ["Carga", "Carga"]]
    categoria = models.CharField(max_length=20,
                                 choices=categorias,
                                 default="Particular")

    precio = models.DecimalField(max_digits=20,
                                 decimal_places=0,
                                 blank=False,
                                 null=False)
    #auto_now_add Se anade una sola vez, cuando se crea el registro
    creacion = models.DateTimeField(auto_now_add=True)
    #auto_now Se modifica con cada cambio que se realize en el registro
    modificacion = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = [("visualizar_catalogo", "Visualizar catalogos")]
      
#function para determinar la condicion de precio seguna su valor.
    #def condicion_precio(self):

      
      #if self.precio >= 0 and self.precio <= 10000:
        #return "Bajo"
      
      #return "Alto"


# medio: 10001 30000
# alto: 30001 a mas

vehiculos/forms.py
from django import forms
from .models import Vehiculo


class VehiculoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(VehiculoForm, self).__init__(*args, **kwargs)
        self.fields['precio'].widget.attrs['class'] = 'form-control'
        self.fields['modelo'].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Vehiculo
        exclude = []

vehiculos/views.py
from django.shortcuts import render
from .forms import VehiculoForm
from .models import Vehiculo


# Create your views here.
def index(request):
    context = {}
    return render(request, "index.html", context)


# Crear una function que se llame v_list
# Que tenga variable context = {}
# Que tenga el return render
# Que llame al archivo list.html

# Dentro de la variable context
# incluir el listado de vehiculos
# Vehiculo.objects.all()
from django.contrib.auth.decorators import login_required, permission_required


@login_required(login_url="/admin/login/")
@permission_required('vehiculos.visualizar_catalogo',
                     login_url="/admin/login/")
def v_list(request):
    datos = Vehiculo.objects.all()
    if request.GET.get('modelo', None) != None: #cuando sea diferente
      datos = datos.filter(modelo__icontains = request.GET.get('modelo'))
      
    if request.GET.get('marca', None) != None: #cuando sea diferente
      datos = datos.filter(marca__icontains = request.GET.get('marca'))
      
    context = {'cars': datos}
    return render(request, "list.html", context)
    # Crear el archivo list.html en templates
    # Crear la url que apunte a v_list
    # vehiculo/list


@login_required(login_url="/admin/login/")
@permission_required('vehiculos.add_vehiculo', login_url="/admin/login/")
def v_add(request):
    if request.method == 'POST':  # Si la peticion proviene de un metodo POST
        data = VehiculoForm(
            request.POST)  # Datos del metodo post inserto en el form
        if data.is_valid():  # Los datos cruzan las validaciones
            data.save()  # Guarda en base de datos

    # Se muestra cuando la peticion no sea POST
    # Se muestra cuando la peticion POST ha terminado
    context = {"form": VehiculoForm()}
    return render(request, "add.html", context)

config/templates/add.html
{% extends 'base.html' %}

{% block content %}
  <h1>Agregar Nuevo Producto</h1>
  <form method="POST" autocomplete="off" >
    {% csrf_token %}
    
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Enviar</button>
  </form>
{% endblock %}

config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="csrf-token" content="{{ csrf_token }}">
    <title>System add Products</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/app.css' %}" />
  </head>
  <body>
    <nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="index.html"> 🛑 Nombre Empresa</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              {% if user.is_authenticated %}
              <a class="nav-link active" aria-current="page" href="#">Hola, {{ user.username }}</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/vehiculo/list">Catálogo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/vehiculo/add">Agregar</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>    
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

config/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>Catálogo de Productos</h1>
{% endblock %}

config/templates/list.html
{% extends 'base.html' %}
{% block content %}
  <h1>Catálogo de Productos</h1>
<style>
.table, th, td {
  border-collapse: collapse;
}
</style>
  <form>
  <table class="table">
    <thead>
      <tr>
        <th>
          <input placeholder="Marca" name="marca" type="text">
        </th>
        <th>
           <input placeholder="Modelo" name="modelo" type="text">
        </th>
        <th>
          <button class="btn btn-primary" type="submit">Consultar</button>
        </th>
      </tr>
      <tr>
        <th>Marca</th>
        <th>Modelo</th>
        <th>Condicion</th>
        <th>Año</th>
        <th>Categoría</th>
        <th>Precio</th>
      </tr>
    </thead>
    <tbody>
      {% for v in cars %}
      <tr>
        <td>{{ v.get_marca_display }}</td>
        <td>{{ v.modelo }}</td>
        <td>{{ v.condicion }}</td>
        <td>{{ v.año }}</td>
        <td>{{ v.categoria }}</td>
        <td>{{ v.precio }}</td>
      </tr>
      {% empty %}
      <tr>
        <td colespan="6"> 🫡 No se encontraron datos del vehículo</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  </form>
{% endblock %}